### ISSUE TITLE
Assigning username to users 

### ISSUE THREAD

**Issue by anastasia-morf** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group3#1]
We have to assign each directory "UserX" a username - what would you like yours to be?

@ltatnell 
@emma4033

**Comment by ltatnell** [comment]
Mine can be a nice simple "Lucas". Thanks Anastasia

**Comment by emma4033** [comment]
I'll be Emma thanks :)

**Comment by anastasia-morf** [comment]
I am having some trouble doing this - is anyone able to help?

@emma4033 @ltatnell @lachlan13893

**Comment by emma4033** [comment]
@anastasia-morf 
I'm working on changing the folder names to the user names, will keep you updated.

**Comment by emma4033** [comment]
I have created a pull request to change the names, please approve :)

**Comment by anastasia-morf** [comment]
Thanks guys - pull request #10 has been approved and I will close this issue now :)
