### ISSUE TITLE
pytest issue

### ISSUE THREAD

**Issue by emma4033** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group3#25]
Hey guys,

I am having issues with testing the functions, I am getting an error with collecting the test_functions.py Notebook. I think it is to do with how I am trying to import the function. Any advice would be greatly appreciated.

Cheers,
Emma

**Comment by anastasia-morf** [comment]
Hi Emma, 
Make sure you have uploaded your code onto the module "functions.py" under the tests/src folder. 
I think that is where your notebooks is importing the functions from.
Let me know if that works.

**Comment by emma4033** [comment]
Thanks Anastasia, it's working now :))
