### ISSUE TITLE
Map program can't find URL

### ISSUE THREAD

**Issue by lachlan13893** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group3#28]
When trying to use map_tiles in MapMaker.ipynb, it is raising an issue where it cannot find a url. 
Error Code is:
HTTPError: HTTP Error 404: Not Found

Others in the group have been unable to help me resolve it. Any advice? @navidcy

**Comment by ltatnell** [comment]
This is due to a spelling issue - it says "physcical" instead of "physical" in my_coastlines. Let me know if this works!

**Comment by lachlan13893** [comment]
It does. Thanks
