### ISSUE TITLE
errror with download_point_data function

### ISSUE THREAD

**Issue by emma4033** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group3#47]
Hey guys,

I am getting an issue with one of my tests for the download_point_data function to do with the url and the import commands in the function. I think it might be an issue with Cloudstor but I am not sure. Have you guys had any problems like this and were able to fix it?

Cheers, 
Emma

**Comment by ltatnell** [comment]
Interesting, I'm not getting that same issue. Maybe try running my code and see if you get the same error (to see if its an issue with your connection). Or maybe cloudstor has fixed itself by now haha

**Comment by emma4033** [comment]
Thanks for the comment Lucas, it appears to be working now so I think it is an issue with the connection to cloudstor.
