### ISSUE TITLE
Test functions for Ana

### ISSUE THREAD

**Issue by emma4033** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group3#51]
Hey @anastasia-morf ,

I have tested all of your functions and they are all working except for the download_point_data, however, I am fairly certain that is an issue with the cloudstor server connection instead of the code or tests (based on the error I am getting). Good work with everything!!! Also, with the my_water_features function we had slightly different variables, I made my oceans=False while it appears you made oceans=True, which you should keep in mind testing my functions.

Cheers,
Emma :)

**Comment by anastasia-morf** [comment]
Thanks Emma, I am testing your functions now too :) I am getting the same errors as you but I've fixed them up to match your code and everything works :) I will close this now.
