### ISSUE TITLE
Tested functions for Lucas

### ISSUE THREAD

**Issue by emma4033** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group3#53]
Hey @ltatnell ,

I have just tested all of your functions and they are all working except for the download_point_data function with the min_magnitude variable, however, I believe Ana already raised an issue and you guys figured that out. Good work with the assignment!!!

Cheers,
Emma

**Comment by ltatnell** [comment]
Yep, we've sorted these! Just a difference with how I've constructed my functions :) Thanks!
