### ISSUE TITLE
How do we want to document what we are doing in REPORT.md?

### ISSUE THREAD

**Issue by ltatnell** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group3#9]
Seems the task is that we all individually make code to create a map and then we write tests for each others code.

We can either document this in the report by name; have a heading like "Anastasia's Code" and then Anastasia documents what she did and we all add how we tester her code, and have a similar heading for each of us.

Or we could document chronologically by date (?), by just saying what we did on what date

Or any other ideas?

@anastasia-morf @emma4033 @lachlan13893

**Comment by emma4033** [comment]
I think doing it by name and date would be the easiest to keep track of changes and testing

**Comment by anastasia-morf** [comment]
I prefer having headings instead, so our individual codes are easier to find and it will reduce the number of documents.

**Comment by ltatnell** [comment]
I feel like it might be more clear for Louis and Navid if we have a heading for each of us, and then whate each of us did on what date for that person's code under that heading

And maybe another section for README.md and other things we all deal with

**Comment by anastasia-morf** [comment]
That sounds good @ltatnell - let's do that.

**Comment by emma4033** [comment]
The makes sense to me @ltatnell, let's go with that format

**Comment by lachlan13893** [comment]
I also think headings, with the date under each heading

**Comment by ltatnell** [comment]
Seems we're all on the same page
